// Date: 30.12.2012 13:52:59
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.lom.lotsomobsmodels;

import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;
@SideOnly(Side.CLIENT)
public class ModelTriceratops extends ModelBase
{
  //fields
    ModelRenderer Body;
    ModelRenderer Leg2;
    ModelRenderer Leg4;
    ModelRenderer Leg1;
    ModelRenderer Leg3;
    ModelRenderer Head;
    ModelRenderer Nose;
    ModelRenderer HornNose;
    ModelRenderer HeadPlate;
    ModelRenderer HornPlateR;
    ModelRenderer HornPlateL;
    ModelRenderer Rug;
    ModelRenderer Tail;
    ModelRenderer TailM;
  
  public ModelTriceratops()
  {
    textureWidth = 512;
    textureHeight = 512;
    
      Body = new ModelRenderer(this, 0, 0);
      Body.addBox(0F, 0F, 0F, 32, 18, 48);
      Body.setRotationPoint(-16F, -6F, 0F);
      Body.setTextureSize(512, 512);
      Body.mirror = true;
      setRotation(Body, 0.0436332F, 0F, 0F);
      Leg2 = new ModelRenderer(this, 0, 0);
      Leg2.addBox(0F, 0F, 0F, 6, 13, 6);
      Leg2.setRotationPoint(-15F, 10F, 1F);
      Leg2.setTextureSize(512, 512);
      Leg2.mirror = true;
      setRotation(Leg2, 0F, 0F, 0F);
      Leg4 = new ModelRenderer(this, 0, 0);
      Leg4.addBox(0F, 0F, 0F, 6, 13, 6);
      Leg4.setRotationPoint(-15F, 10F, 42F);
      Leg4.setTextureSize(512, 512);
      Leg4.mirror = true;
      setRotation(Leg4, 0F, 0F, 0F);
      Leg1 = new ModelRenderer(this, 0, 0);
      Leg1.addBox(0F, 0F, 0F, 6, 13, 6);
      Leg1.setRotationPoint(9F, 10F, 1F);
      Leg1.setTextureSize(512, 512);
      Leg1.mirror = true;
      setRotation(Leg1, 0F, 0F, 0F);
      Leg3 = new ModelRenderer(this, 0, 0);
      Leg3.addBox(0F, 0F, 0F, 6, 13, 6);
      Leg3.setRotationPoint(9F, 10F, 42F);
      Leg3.setTextureSize(512, 512);
      Leg3.mirror = true;
      setRotation(Leg3, 0F, 0F, 0F);
      Head = new ModelRenderer(this, 0, 150);
      Head.addBox(0F, 0F, -1F, 20, 12, 16);
      Head.setRotationPoint(-10F, -8F, -15F);
      Head.setTextureSize(512, 512);
      Head.mirror = true;
      setRotation(Head, 0.1858931F, 0F, 0F);
      Nose = new ModelRenderer(this, 0, 125);
      Nose.addBox(0F, 0F, 0F, 9, 5, 11);
      Nose.setRotationPoint(-5F, -1F, -25F);
      Nose.setTextureSize(512, 512);
      Nose.mirror = true;
      setRotation(Nose, 0.0743592F, 0F, 0F);
      HornNose = new ModelRenderer(this, 0, 100);
      HornNose.addBox(0F, 0F, 0F, 3, 4, 3);
      HornNose.setRotationPoint(-2F, -5F, -23F);
      HornNose.setTextureSize(512, 512);
      HornNose.mirror = true;
      setRotation(HornNose, 0F, 0F, 0F);
      HeadPlate = new ModelRenderer(this, 0, 186);
      HeadPlate.addBox(0F, 0F, 0F, 34, 28, 2);
      HeadPlate.setRotationPoint(-17F, -22F, 2F);
      HeadPlate.setTextureSize(512, 512);
      HeadPlate.mirror = true;
      setRotation(HeadPlate, -0.2519884F, 0F, 0F);
      HornPlateR = new ModelRenderer(this, 0, 224);
      HornPlateR.addBox(0F, 0F, 0F, 3, 15, 3);
      HornPlateR.setRotationPoint(-14F, -16F, 1F);
      HornPlateR.setTextureSize(512, 512);
      HornPlateR.mirror = true;
      setRotation(HornPlateR, -1.970466F, 0F, 0F);
      HornPlateL = new ModelRenderer(this, 0, 224);
      HornPlateL.addBox(0F, 0F, 0F, 3, 15, 3);
      HornPlateL.setRotationPoint(11F, -16F, 1F);
      HornPlateL.setTextureSize(512, 512);
      HornPlateL.mirror = true;
      setRotation(HornPlateL, -1.970466F, 0F, 0F);
      Rug = new ModelRenderer(this, 168, 0);
      Rug.addBox(0F, 0F, 0F, 20, 7, 43);
      Rug.setRotationPoint(-10F, -13F, 0F);
      Rug.setTextureSize(512, 512);
      Rug.mirror = true;
      setRotation(Rug, 0.0436332F, 0F, 0F);
      Tail = new ModelRenderer(this, 310, 0);
      Tail.addBox(0F, 0F, 0F, 20, 10, 28);
      Tail.setRotationPoint(-10F, -14F, 42F);
      Tail.setTextureSize(512, 512);
      Tail.mirror = true;
      setRotation(Tail, -0.2974289F, 0F, 0F);
      TailM = new ModelRenderer(this, 435, 0);
      TailM.addBox(0F, 0F, 0F, 14, 6, 18);
      TailM.setRotationPoint(-7F, -2F, 65F);
      TailM.setTextureSize(512, 512);
      TailM.mirror = true;
      setRotation(TailM, 0.0743572F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Body.render(f5);
    Leg2.render(f5);
    Leg4.render(f5);
    Leg1.render(f5);
    Leg3.render(f5);
    Head.render(f5);
    Nose.render(f5);
    HornNose.render(f5);
    HeadPlate.render(f5);
    HornPlateR.render(f5);
    HornPlateL.render(f5);
    Rug.render(f5);
    Tail.render(f5);
    TailM.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
    Leg1.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
    Leg2.rotateAngleX = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1;
    Leg3.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
    Leg4.rotateAngleX = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1;
  }

}
